name: Pylint

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
        python setup.py install
    - name: Analysing the code with pylint
      run: |
        pylint --disable=trailing-whitespace,invalid-name,fixme,line-too-long,missing-module-docstring,redefined-builtin,wrong-import-position,missing-function-docstring,no-member,too-many-locals,too-many-branches,too-many-statements,too-many-arguments,arguments-differ,anomalous-backslash-in-string,unexpected-keyword-arg,unused-argument,duplicate-code,protected-access,unnecessary-dunder-call,use-dict-literal,multiple-statements,broad-exception-raised,superfluous-parens, $(git ls-files '*.py')
